// <auto-generated />
using System;
using Bank.Deposits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Deposits.Data.Migrations
{
    [DbContext(typeof(DepositsDbContext))]
    partial class DepositsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Bank.Deposits.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChartAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChartAccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChartAccountId = 1,
                            CurrencyId = 1,
                            NameEn = "Bank cash",
                            NameRu = "Касса банка",
                            Number = "1010000000013"
                        },
                        new
                        {
                            Id = 2,
                            ChartAccountId = 2,
                            CurrencyId = 1,
                            NameEn = "Correspondent account in the National Bank of Belarus",
                            NameRu = "Корреспондентский счёт в НБ РБ",
                            Number = "1201000000019"
                        },
                        new
                        {
                            Id = 3,
                            ChartAccountId = 8,
                            CurrencyId = 1,
                            NameEn = "Bank development fund",
                            NameRu = "Фонд развития банка",
                            Number = "7327000000010"
                        });
                });

            modelBuilder.Entity("Bank.Deposits.Models.BankState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDate = new DateOnly(2026, 9, 20)
                        });
                });

            modelBuilder.Entity("Bank.Deposits.Models.ChartAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChartAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1010",
                            NameEn = "Bank cash",
                            NameRu = "Касса банка",
                            Nature = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "1201",
                            NameEn = "Correspondent account in the National Bank of Belarus",
                            NameRu = "Корреспондентский счёт в НБ РБ",
                            Nature = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "3014",
                            NameEn = "Current accounts of individuals",
                            NameRu = "Текущие счета физических лиц",
                            Nature = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "3404",
                            NameEn = "Demand deposits of individuals",
                            NameRu = "Вклады до востребования физических лиц",
                            Nature = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "3414",
                            NameEn = "Term deposits of individuals",
                            NameRu = "Срочные вклады физических лиц",
                            Nature = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "3470",
                            NameEn = "Accrued interest on demand deposits",
                            NameRu = "Начисленные проценты по вкладам до востребования",
                            Nature = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "3471",
                            NameEn = "Accrued interest on term deposits",
                            NameRu = "Начисленные проценты по срочным вкладам",
                            Nature = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "7327",
                            NameEn = "Bank development fund",
                            NameRu = "Фонд развития банка",
                            Nature = 2
                        });
                });

            modelBuilder.Entity("Bank.Deposits.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BYN",
                            NameEn = "Belarusian ruble",
                            NameRu = "Белорусский рубль"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            NameEn = "US dollar",
                            NameRu = "Доллар США"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EUR",
                            NameEn = "Euro",
                            NameRu = "Евро"
                        });
                });

            modelBuilder.Entity("Bank.Deposits.Models.DepositContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterestAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastInterestPaidOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrincipalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InterestAccountId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PrincipalAccountId");

                    b.HasIndex("ProductId");

                    b.ToTable("DepositContracts");
                });

            modelBuilder.Entity("Bank.Deposits.Models.DepositProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestChartAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrincipalChartAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Revocable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InterestChartAccountId");

                    b.HasIndex("PrincipalChartAccountId");

                    b.ToTable("DepositProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualRate = 5.5m,
                            Code = "ALFA_SAFE",
                            CurrencyId = 1,
                            InterestChartAccountId = 6,
                            InterestSchedule = 1,
                            MaxAmount = 20000m,
                            MinAmount = 200m,
                            NameEn = "Alfa Safe (revocable)",
                            NameRu = "Альфа Сейф (отзывный)",
                            PrincipalChartAccountId = 4,
                            Revocable = true,
                            TermMonths = 13
                        },
                        new
                        {
                            Id = 2,
                            AnnualRate = 12m,
                            Code = "ALFA_VKLAD",
                            CurrencyId = 1,
                            InterestChartAccountId = 7,
                            InterestSchedule = 2,
                            MaxAmount = 5000000m,
                            MinAmount = 50m,
                            NameEn = "Alfa Vklad (irrevocable)",
                            NameRu = "Альфа Вклад (безотзывный)",
                            PrincipalChartAccountId = 5,
                            Revocable = false,
                            TermMonths = 13
                        });
                });

            modelBuilder.Entity("Bank.Deposits.Models.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountByn")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebitAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreditAccountId");

                    b.HasIndex("DebitAccountId");

                    b.ToTable("LedgerEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000000m,
                            AmountByn = 1000000m,
                            BookedOn = new DateOnly(2026, 9, 20),
                            CreditAccountId = 3,
                            DebitAccountId = 2,
                            Operation = "sfrbCapital",
                            Rate = 1m
                        });
                });

            modelBuilder.Entity("Bank.Deposits.Models.BankAccount", b =>
                {
                    b.HasOne("Bank.Deposits.Models.ChartAccount", "ChartAccount")
                        .WithMany()
                        .HasForeignKey("ChartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChartAccount");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Bank.Deposits.Models.DepositContract", b =>
                {
                    b.HasOne("Bank.Deposits.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.BankAccount", "InterestAccount")
                        .WithMany()
                        .HasForeignKey("InterestAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.BankAccount", "PrincipalAccount")
                        .WithMany()
                        .HasForeignKey("PrincipalAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.DepositProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("InterestAccount");

                    b.Navigation("PrincipalAccount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bank.Deposits.Models.DepositProduct", b =>
                {
                    b.HasOne("Bank.Deposits.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.ChartAccount", "InterestChartAccount")
                        .WithMany()
                        .HasForeignKey("InterestChartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.ChartAccount", "PrincipalChartAccount")
                        .WithMany()
                        .HasForeignKey("PrincipalChartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("InterestChartAccount");

                    b.Navigation("PrincipalChartAccount");
                });

            modelBuilder.Entity("Bank.Deposits.Models.LedgerEntry", b =>
                {
                    b.HasOne("Bank.Deposits.Models.DepositContract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bank.Deposits.Models.BankAccount", "CreditAccount")
                        .WithMany()
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Deposits.Models.BankAccount", "DebitAccount")
                        .WithMany()
                        .HasForeignKey("DebitAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("CreditAccount");

                    b.Navigation("DebitAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
