// <auto-generated />
using System;
using Bank.Credits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Credits.Data.Migrations
{
    [DbContext(typeof(CreditsDbContext))]
    partial class CreditsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Bank.Credits.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChartAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChartAccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChartAccountId = 1,
                            CurrencyId = 1,
                            NameEn = "Bank cash",
                            NameRu = "Касса банка",
                            Number = "1010000000013"
                        },
                        new
                        {
                            Id = 2,
                            ChartAccountId = 2,
                            CurrencyId = 1,
                            NameEn = "Correspondent account in the National Bank of Belarus",
                            NameRu = "Корреспондентский счёт в НБ РБ",
                            Number = "1201000000019"
                        },
                        new
                        {
                            Id = 3,
                            ChartAccountId = 7,
                            CurrencyId = 1,
                            NameEn = "Bank development fund",
                            NameRu = "Фонд развития банка",
                            Number = "7327000000010"
                        },
                        new
                        {
                            Id = 4,
                            ChartAccountId = 9,
                            CurrencyId = 1,
                            NameEn = "Settlements with mobile operators",
                            NameRu = "Расчёты с операторами связи",
                            Number = "3819000000018"
                        });
                });

            modelBuilder.Entity("Bank.Credits.Models.BankCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardAccountId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("CreditContractId");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("Bank.Credits.Models.BankState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDate = new DateOnly(2026, 9, 20)
                        });
                });

            modelBuilder.Entity("Bank.Credits.Models.ChartAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChartAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1010",
                            NameEn = "Bank cash",
                            NameRu = "Касса банка",
                            Nature = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "1201",
                            NameEn = "Correspondent account in the National Bank of Belarus",
                            NameRu = "Корреспондентский счёт в НБ РБ",
                            Nature = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "2410",
                            NameEn = "Short-term loans to individuals",
                            NameRu = "Краткосрочные кредиты физическим лицам",
                            Nature = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "2420",
                            NameEn = "Long-term loans to individuals",
                            NameRu = "Долгосрочные кредиты физическим лицам",
                            Nature = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "2471",
                            NameEn = "Accrued interest on short-term loans to individuals",
                            NameRu = "Начисленные проценты по краткосрочным кредитам физическим лицам",
                            Nature = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "2472",
                            NameEn = "Accrued interest on long-term loans to individuals",
                            NameRu = "Начисленные проценты по долгосрочным кредитам физическим лицам",
                            Nature = 1
                        },
                        new
                        {
                            Id = 7,
                            Code = "7327",
                            NameEn = "Bank development fund",
                            NameRu = "Фонд развития банка",
                            Nature = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "3014",
                            NameEn = "Card accounts of individuals",
                            NameRu = "Карт-счета физических лиц",
                            Nature = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "3819",
                            NameEn = "Settlements with mobile operators",
                            NameRu = "Расчёты с операторами связи",
                            Nature = 2
                        });
                });

            modelBuilder.Entity("Bank.Credits.Models.CreditContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterestAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastPaymentOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaidPeriods")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrincipalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RemainingPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InterestAccountId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PrincipalAccountId");

                    b.HasIndex("ProductId");

                    b.ToTable("CreditContracts");
                });

            modelBuilder.Entity("Bank.Credits.Models.CreditProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestChartAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrincipalChartAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepaymentSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InterestChartAccountId");

                    b.HasIndex("PrincipalChartAccountId");

                    b.ToTable("CreditProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualRate = 18.1m,
                            Code = "ALFA_CASH",
                            CurrencyId = 1,
                            InterestChartAccountId = 5,
                            MaxAmount = 20000m,
                            MinAmount = 1000m,
                            NameEn = "Cash loan (annuity)",
                            NameRu = "Кредит наличными (аннуитет)",
                            PrincipalChartAccountId = 3,
                            RepaymentSchedule = 1,
                            TermMonths = 12
                        },
                        new
                        {
                            Id = 2,
                            AnnualRate = 18.1m,
                            Code = "ALFA_ONLINE",
                            CurrencyId = 1,
                            InterestChartAccountId = 6,
                            MaxAmount = 7000m,
                            MinAmount = 500m,
                            NameEn = "Online loan (interest monthly, principal at term end)",
                            NameRu = "Кредит онлайн (проценты ежемесячно, тело в конце срока)",
                            PrincipalChartAccountId = 4,
                            RepaymentSchedule = 2,
                            TermMonths = 24
                        });
                });

            modelBuilder.Entity("Bank.Credits.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BYN",
                            NameEn = "Belarusian ruble",
                            NameRu = "Белорусский рубль"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            NameEn = "US dollar",
                            NameRu = "Доллар США"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EUR",
                            NameEn = "Euro",
                            NameRu = "Евро"
                        });
                });

            modelBuilder.Entity("Bank.Credits.Models.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountByn")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebitAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreditAccountId");

                    b.HasIndex("DebitAccountId");

                    b.ToTable("LedgerEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000000m,
                            AmountByn = 1000000m,
                            BookedOn = new DateOnly(2026, 9, 20),
                            CreditAccountId = 3,
                            DebitAccountId = 2,
                            Operation = "sfrbCapital",
                            Rate = 1m
                        });
                });

            modelBuilder.Entity("Bank.Credits.Models.BankAccount", b =>
                {
                    b.HasOne("Bank.Credits.Models.ChartAccount", "ChartAccount")
                        .WithMany()
                        .HasForeignKey("ChartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChartAccount");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Bank.Credits.Models.BankCard", b =>
                {
                    b.HasOne("Bank.Credits.Models.BankAccount", "CardAccount")
                        .WithMany()
                        .HasForeignKey("CardAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.CreditContract", "CreditContract")
                        .WithMany()
                        .HasForeignKey("CreditContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardAccount");

                    b.Navigation("CreditContract");
                });

            modelBuilder.Entity("Bank.Credits.Models.CreditContract", b =>
                {
                    b.HasOne("Bank.Credits.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.BankAccount", "InterestAccount")
                        .WithMany()
                        .HasForeignKey("InterestAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.BankAccount", "PrincipalAccount")
                        .WithMany()
                        .HasForeignKey("PrincipalAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.CreditProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("InterestAccount");

                    b.Navigation("PrincipalAccount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bank.Credits.Models.CreditProduct", b =>
                {
                    b.HasOne("Bank.Credits.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.ChartAccount", "InterestChartAccount")
                        .WithMany()
                        .HasForeignKey("InterestChartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.ChartAccount", "PrincipalChartAccount")
                        .WithMany()
                        .HasForeignKey("PrincipalChartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("InterestChartAccount");

                    b.Navigation("PrincipalChartAccount");
                });

            modelBuilder.Entity("Bank.Credits.Models.LedgerEntry", b =>
                {
                    b.HasOne("Bank.Credits.Models.CreditContract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bank.Credits.Models.BankAccount", "CreditAccount")
                        .WithMany()
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Credits.Models.BankAccount", "DebitAccount")
                        .WithMany()
                        .HasForeignKey("DebitAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("CreditAccount");

                    b.Navigation("DebitAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
