// <auto-generated />
using System;
using Bank.Clients.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Clients.Data.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Bank.Clients.Models.Citizenship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Citizenships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEn = "Belarus",
                            NameRu = "Беларусь"
                        },
                        new
                        {
                            Id = 2,
                            NameEn = "Russia",
                            NameRu = "Россия"
                        },
                        new
                        {
                            Id = 3,
                            NameEn = "Kazakhstan",
                            NameRu = "Казахстан"
                        },
                        new
                        {
                            Id = 4,
                            NameEn = "Other",
                            NameRu = "Другое"
                        });
                });

            modelBuilder.Entity("Bank.Clients.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEn = "Minsk",
                            NameRu = "Минск"
                        },
                        new
                        {
                            Id = 2,
                            NameEn = "Brest",
                            NameRu = "Брест"
                        },
                        new
                        {
                            Id = 3,
                            NameEn = "Grodno",
                            NameRu = "Гродно"
                        },
                        new
                        {
                            Id = 4,
                            NameEn = "Vitebsk",
                            NameRu = "Витебск"
                        },
                        new
                        {
                            Id = 5,
                            NameEn = "Mogilev",
                            NameRu = "Могилёв"
                        },
                        new
                        {
                            Id = 6,
                            NameEn = "Gomel",
                            NameRu = "Гомель"
                        });
                });

            modelBuilder.Entity("Bank.Clients.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("CitizenshipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisabilityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportSeries")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pensioner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationCityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResidenceAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceCityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Workplace")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitizenshipId");

                    b.HasIndex("DisabilityId");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("RegistrationCityId");

                    b.HasIndex("ResidenceCityId");

                    b.HasIndex("PassportSeries", "PassportNumber")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName", "Patronymic", "BirthDate")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2003, 5, 15),
                            BirthPlace = "Minsk",
                            CitizenshipId = 1,
                            DisabilityId = 1,
                            Email = "n.glushachenko@example.com",
                            FirstName = "Nikita",
                            HomePhone = "+375 (17) 234-56-78",
                            IdentificationNumber = "1505033A015PB7",
                            IssueDate = new DateOnly(2019, 6, 20),
                            IssuedBy = "Central District Police Department, Minsk",
                            LastName = "Glushachenko",
                            MaritalStatusId = 1,
                            MobilePhone = "+375 (29) 111-22-33",
                            MonthlyIncome = 900m,
                            PassportNumber = "7654321",
                            PassportSeries = "AB",
                            Patronymic = "Sergeevich",
                            Pensioner = false,
                            Position = "Student",
                            RegistrationCityId = 1,
                            ResidenceAddress = "Independence Ave. 10, apt. 5",
                            ResidenceCityId = 1,
                            Workplace = "BSUIR"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1988, 3, 12),
                            BirthPlace = "Minsk",
                            CitizenshipId = 1,
                            DisabilityId = 1,
                            Email = "p.ivanov@example.com",
                            FirstName = "Petr",
                            IdentificationNumber = "1203881A013PB2",
                            IssueDate = new DateOnly(2015, 4, 1),
                            IssuedBy = "Moskovsky District Police Department, Minsk",
                            LastName = "Ivanov",
                            MaritalStatusId = 2,
                            MobilePhone = "+375 (29) 555-44-33",
                            MonthlyIncome = 2400m,
                            PassportNumber = "1234567",
                            PassportSeries = "BM",
                            Patronymic = "Alekseevich",
                            Pensioner = false,
                            Position = "Economist",
                            RegistrationCityId = 1,
                            ResidenceAddress = "Pobediteley Ave. 21, apt. 14",
                            ResidenceCityId = 1,
                            Workplace = "Belarusbank"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1991, 11, 2),
                            BirthPlace = "Brest",
                            CitizenshipId = 1,
                            DisabilityId = 1,
                            FirstName = "Maria",
                            HomePhone = "+375 (16) 221-10-10",
                            IdentificationNumber = "0211912B024PB3",
                            IssueDate = new DateOnly(2016, 11, 15),
                            IssuedBy = "Leninsky District Police Department, Brest",
                            LastName = "Petrova",
                            MaritalStatusId = 2,
                            MobilePhone = "+375 (33) 222-33-44",
                            MonthlyIncome = 1800m,
                            PassportNumber = "2345678",
                            PassportSeries = "HB",
                            Patronymic = "Alexandrovna",
                            Pensioner = false,
                            Position = "Accountant",
                            RegistrationCityId = 2,
                            ResidenceAddress = "Sovetskaya St. 8, apt. 3",
                            ResidenceCityId = 2,
                            Workplace = "Horizon Ltd."
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1975, 7, 28),
                            BirthPlace = "Grodno",
                            CitizenshipId = 1,
                            DisabilityId = 4,
                            Email = "a.sidorov@example.com",
                            FirstName = "Alexey",
                            IdentificationNumber = "2807753C035PB4",
                            IssueDate = new DateOnly(2014, 8, 10),
                            IssuedBy = "Oktyabrsky District Police Department, Grodno",
                            LastName = "Sidorov",
                            MaritalStatusId = 3,
                            MobilePhone = "+375 (44) 777-88-99",
                            MonthlyIncome = 2100m,
                            PassportNumber = "3456789",
                            PassportSeries = "KH",
                            Patronymic = "Petrovich",
                            Pensioner = false,
                            Position = "Engineer",
                            RegistrationCityId = 3,
                            ResidenceAddress = "Gorky St. 45, apt. 12",
                            ResidenceCityId = 3,
                            Workplace = "Grodno Azot"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1958, 1, 9),
                            BirthPlace = "Vitebsk",
                            CitizenshipId = 1,
                            DisabilityId = 3,
                            FirstName = "Anna",
                            HomePhone = "+375 (21) 360-12-34",
                            IdentificationNumber = "0901584K046PB5",
                            IssueDate = new DateOnly(2018, 2, 14),
                            IssuedBy = "Zheleznodorozhny District Police Department, Vitebsk",
                            LastName = "Kozlova",
                            MaritalStatusId = 4,
                            MonthlyIncome = 650m,
                            PassportNumber = "4567890",
                            PassportSeries = "MP",
                            Patronymic = "Viktorovna",
                            Pensioner = true,
                            RegistrationCityId = 4,
                            ResidenceAddress = "Lenin St. 3, apt. 7",
                            ResidenceCityId = 4
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1995, 9, 21),
                            BirthPlace = "Gomel",
                            CitizenshipId = 2,
                            DisabilityId = 1,
                            Email = "d.novikov@example.com",
                            FirstName = "Dmitry",
                            IdentificationNumber = "2109955E057PB6",
                            IssueDate = new DateOnly(2021, 10, 5),
                            IssuedBy = "Central District Police Department, Gomel",
                            LastName = "Novikov",
                            MaritalStatusId = 1,
                            MobilePhone = "+375 (25) 101-20-30",
                            MonthlyIncome = 3500m,
                            PassportNumber = "5678901",
                            PassportSeries = "MC",
                            Patronymic = "Olegovich",
                            Pensioner = false,
                            Position = "Software Developer",
                            RegistrationCityId = 1,
                            ResidenceAddress = "Barykina St. 120, apt. 44",
                            ResidenceCityId = 6,
                            Workplace = "EPAM Systems"
                        });
                });

            modelBuilder.Entity("Bank.Clients.Models.Disability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Disabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEn = "None",
                            NameRu = "Нет"
                        },
                        new
                        {
                            Id = 2,
                            NameEn = "Group I",
                            NameRu = "I группа"
                        },
                        new
                        {
                            Id = 3,
                            NameEn = "Group II",
                            NameRu = "II группа"
                        },
                        new
                        {
                            Id = 4,
                            NameEn = "Group III",
                            NameRu = "III группа"
                        });
                });

            modelBuilder.Entity("Bank.Clients.Models.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEn = "Single",
                            NameRu = "Холост / не замужем"
                        },
                        new
                        {
                            Id = 2,
                            NameEn = "Married",
                            NameRu = "Женат / замужем"
                        },
                        new
                        {
                            Id = 3,
                            NameEn = "Divorced",
                            NameRu = "Разведён(а)"
                        },
                        new
                        {
                            Id = 4,
                            NameEn = "Widowed",
                            NameRu = "Вдовец / вдова"
                        });
                });

            modelBuilder.Entity("Bank.Clients.Models.Client", b =>
                {
                    b.HasOne("Bank.Clients.Models.Citizenship", "Citizenship")
                        .WithMany()
                        .HasForeignKey("CitizenshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Clients.Models.Disability", "Disability")
                        .WithMany()
                        .HasForeignKey("DisabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Clients.Models.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Clients.Models.City", "RegistrationCity")
                        .WithMany()
                        .HasForeignKey("RegistrationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.Clients.Models.City", "ResidenceCity")
                        .WithMany()
                        .HasForeignKey("ResidenceCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizenship");

                    b.Navigation("Disability");

                    b.Navigation("MaritalStatus");

                    b.Navigation("RegistrationCity");

                    b.Navigation("ResidenceCity");
                });
#pragma warning restore 612, 618
        }
    }
}
